### ISSUE TITLE
高qps情况下内存暴增

### ISSUE THREAD

**Issue by iliuyt** [SkyAPM/SkyAPM-nodejs#107]
### 内存暴增

 本地通过docker 启用skywalking 7，nodejs使用skyapm-nodejs调用skywalking, qps越高持续时间越长内存增的越快，平均约qps:3000 每十秒增加500M，

![image](https://user-images.githubusercontent.com/10969445/80341084-6046a000-8894-11ea-8fe5-fc5762267983.png)

### demo压测代码

``` javascirpt
require("skyapm-nodejs").start({
  serviceName: "local-demo",
  directServers: "127.0.0.1:11800",
});

const http = require("http");
const server = http.createServer((req, res) => {
  res.end("success");
});
server.listen(8000, function() {
  console.log("http://127.0.0.1:8000/");
});

```

**Comment by kezhenxu94** [comment]
@iliuyt 我这边使用你的 demo 代码无法复现, 加大 qps 也无法复现

![image](https://user-images.githubusercontent.com/15965696/82864424-17e3d600-9f57-11ea-993d-ef10e9ab1d59.png)

**Comment by iliuyt** [comment]
@kezhenxu94 

以下是我的环境

##### es集群
``` yaml
version: "2.0"
services:
   elasticsearch-central:
      image: elasticsearch:6.5.0
      container_name: es1
      volumes:
         - ./node/es1/data:/usr/share/elasticsearch/data
         - ./node/es1/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      environment:
         - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
         - ES_CLUSTERNAME=elasticsearch
      command: elasticsearch
      ports:
         - "9200:9200"
         - "9300:9300"
      networks:
         default:
            ipv4_address: 172.21.0.100
   elasticsearch-data:
      image: elasticsearch:6.5.0
      container_name: es2
      volumes:
         - ./node/es2/data:/usr/share/elasticsearch/data
         - ./node/es2/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      environment:
         - bootstrap.memory_lock=true
         - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
         - ES_CLUSTERNAME=elasticsearch
      command: elasticsearch
      ports:
         - "9201:9200"
         - "9301:9300"
      links:
         - elasticsearch-central:elasticsearch
      networks:
         default:
            ipv4_address: 172.21.0.101
   elasticsearch-head:
      image: mobz/elasticsearch-head:5
      container_name: head
      volumes:
         - ./head/Gruntfile.js:/usr/src/app/Gruntfile.js
         - ./head/_site/app.js:/usr/src/app/_site/app.js
      ports:
         - "9100:9100"
      links:
         - elasticsearch-central:elasticsearch
      networks:
         default:
            ipv4_address: 172.21.0.102

networks:
   default:
      external:
         name: common

```

#### skywalking
``` yaml
version: '3.3'
services:
  oap:
    image: apache/skywalking-oap-server:7.0.0-es6
    container_name: oap
    restart: always
    ports:
      - 11800:11800
      - 12800:12800
    environment:
      - SW_STORAGE=elasticsearch #Es的存储
      - SW_STORAGE_ES_CLUSTER_NODES=172.21.0.100:9200
      - TZ=Asia/Shanghai
    networks:
      default:
        ipv4_address: 172.21.0.201
  ui:
    image: apache/skywalking-ui:7.0.0
    container_name: ui
    depends_on:
      - oap
    links:
      - oap
    restart: always
    ports:
      - 18080:8080 #默认8080端口，这里设置18080映射到宿主机，可修改
    environment:
      collector.ribbon.listOfServers: 172.21.0.201:12800
    networks:
      default:
        ipv4_address: 172.21.0.202

networks:
  default:
    external:
      name: common
```

##### 其他信息

* nodejs v10.16.3
* macos 10.15.2
* skyapm-ndoejs 1.2.0
* npm 源为https://registry.npmjs.org/
